# 2D MRI program configuration
description:
  A 2D MRI experiment.
executable: 2D_SLICE_MRI.elf
action:
  offset: 0x0
  values:
    stop: 0
    run: 1
status:
  offset: 0x4
  values:
    uninitialised: 1
    running: 2
    capture: 3
    finished: 10
progress:
  offset: 0x1c
  limit: ${{scans}-1}
output:
  type: DMA
  dtype: complex64
  offset: 0x0
  block_count: 1
  block_length: ${{samples}}
  block_skip: 7
  rotbuf: true
  rotbuf_total: ${{scans}}
  rotbuf_length_offset: 0x30
  rotbuf_read_index_offset: 0x34
  rotbuf_write_index_offset: 0x38
  scale_factor: 1
postprocess:
  decimation: 10
adc_overflow_count:
  offset: 0x20
soft_pulse:
  pulse_width: ${{soft_pulse_width_90}*0.000000001}  # in seconds
  slice_width: ${{slice_90}}  # in meters
  shape_len_offset: 0x140
  shape_len_dtype: uint32
  shape_spacing_offset: 0x144
  shape_spacing_dtype: uint32
  shape_spacing_scaling: 1000000000
  shape_points_offset: 0x200
  shape_points_dtype: float32
  max_len: 256
parameters:
  freq:
    dtype: float64
    unit: MHz
    shared: true
    group: pulse
  soft_pulse_amp_90:
    offset: 0x98
    dtype: float32
    min: 0
    max: 100
    unit: '%'
    scaling: 0.01
    group: pulse
  soft_pulse_width_90:
    offset: 0xa8
    dtype: uint32
    min: 1
    max: 5000
    unit: us
    scaling: 1000
    group: pulse
  slice_90:
    dtype: float32
    min: 0
    max: 10
    unit: mm
    scaling: 0.001
    group: pulse
  amp_180:
    offset: 0xa0
    dtype: float32
    min: 0
    max: 100
    unit: '%'
    scaling: 0.01
    shared: true
    group: pulse
  width_180:
    offset: 0xac
    dtype: uint32
    min: 1
    max: 5000
    unit: us
    scaling: 1000
    shared: true
    group: pulse
  echo_time:
    dtype: uint32
    min: 1
    unit: us
    scaling: 1000
    group: pulse
  echo_shift:
    dtype: int32
    unit: us
    scaling: 1000
    group: acquisition
  rep_time:
    offset: 0xd4
    dtype: uint64
    min: 0
    unit: s
    scaling: 1000000000
    group: pulse
  samples:
    offset: 0xc4
    dtype: uint32
    min: 1
    max: 100000
    scaling: 10 # for the post decimation
    group: acquisition
  dwell_time:
    offset: 0xcc
    dtype: uint32
    min: 0.5
    max: 400
    unit: us
    scaling: 10 # *100 to convert to hardware decimation, /10 for the post decimation
    group: acquisition
  scans:
    offset: 0xd0
    dtype: uint32
    min: 1
    group: pulse
  shim_X:
    offset: 0xec
    dtype: int32
    min: -32768
    max: 32767
    shared: true
    group: shim
  shim_Y:
    offset: 0xf0
    dtype: int32
    min: -32768
    max: 32767
    shared: true
    group: shim
  shim_Z:
    offset: 0xf4
    dtype: int32
    min: -32768
    max: 32767
    shared: true
    group: shim
  shim_Z2:
    offset: 0xf8
    dtype: int32
    min: -32768
    max: 32767
    shared: true
    group: shim
  shim_ZX:
    offset: 0xfc
    dtype: int32
    min: -32768
    max: 32767
    shared: true
    group: shim
  shim_ZY:
    offset: 0x100
    dtype: int32
    min: -32768
    max: 32767
    shared: true
    group: shim
  shim_XY:
    offset: 0x104
    dtype: int32
    min: -32768
    max: 32767
    shared: true
    group: shim
  shim_X2Y2:
    offset: 0x108
    dtype: int32
    min: -32768
    max: 32767
    shared: true
    group: shim
  slice_GX:
    dtype: int32
    min: -32768
    max: 32767
    group: gradients
  slice_GY:
    dtype: int32
    min: -32768
    max: 32767
    group: gradients
  slice_GZ:
    dtype: int32
    min: -32768
    max: 32767
    group: gradients
  read_GX:
    dtype: int32
    min: -32768
    max: 32767
    group: gradients
  read_GY:
    dtype: int32
    min: -32768
    max: 32767
    group: gradients
  read_GZ:
    dtype: int32
    min: -32768
    max: 32767
    group: gradients
  phase_GX:
    dtype: int32
    min: -32768
    max: 32767
    group: gradients
  phase_GY:
    dtype: int32
    min: -32768
    max: 32767
    group: gradients
  phase_GZ:
    dtype: int32
    min: -32768
    max: 32767
    group: gradients
derived_parameters:
  GX1:
    offset: 0x10c
    dtype: int32
    value: ${{shim_X} + {phase_GX} + {read_GX}}
    min: -32768
    max: 32767
  GY1:
    offset: 0x110
    dtype: int32
    value: ${{shim_Y} + {phase_GY} + {read_GY}}
    min: -32768
    max: 32767
  GZ1:
    offset: 0x114
    dtype: int32
    value: ${{shim_Z} + {phase_GZ} + {read_GZ}}
    min: -32768
    max: 32767
  GX2:
    offset: 0x118
    dtype: int32
    value: ${{shim_X} + {read_GX}}
    min: -32768
    max: 32767
  GY2:
    offset: 0x11c
    dtype: int32
    value: ${{shim_Y} + {read_GY}}
    min: -32768
    max: 32767
  GZ2:
    offset: 0x120
    dtype: int32
    value: ${{shim_Z} + {read_GZ}}
    min: -32768
    max: 32767
  GX3:
    offset: 0x124
    dtype: int32
    value: ${{shim_X} + {slice_GX}}
    min: -32768
    max: 32767
  GY3:
    offset: 0x128
    dtype: int32
    value: ${{shim_Y} + {slice_GY}}
    min: -32768
    max: 32767
  GZ3:
    offset: 0x12c
    dtype: int32
    value: ${{shim_Z} + {slice_GZ}}
    min: -32768
    max: 32767
  GX4:
    offset: 0x130
    dtype: int32
    value: ${{shim_X} - {slice_GX}}
    min: -32768
    max: 32767
  GY4:
    offset: 0x134
    dtype: int32
    value: ${{shim_Y} - {slice_GY}}
    min: -32768
    max: 32767
  GZ4:
    offset: 0x138
    dtype: int32
    value: ${{shim_Z} - {slice_GZ}}
    min: -32768
    max: 32767
  unslice_time:
    offset: 0x13c
    dtype: uint32
    value: ${{soft_pulse_width_90}/2}
    min: 10000
  T1:
    offset: 0xb0
    dtype: uint32
    value: ${{samples}*{dwell_time}*5}
    min: 50000
  T2:
    offset: 0xb4
    dtype: uint32
    value: ${{echo_time} - ({soft_pulse_width_90} + {width_180} + {samples}*{dwell_time}*10)/2 - {unslice_time}}
    min: 50000
  T3:
    offset: 0xb8
    dtype: uint32
    value: ${{echo_time} - ({width_180} + {samples}*{dwell_time}*10)/2 + {echo_shift} - 7*{dwell_time}*10}
    min: 10000
  duty_cycle:
    value: ${({width_180}+{soft_pulse_width_90})/{rep_time}}
    max: 0.1
  ignore_samples:
    offset: 0xc8
    dtype: uint32
    value: 7
  freqTx:
    offset: 0x80
    dtype: float64
    value: ${{freq}}
  freqRx:
    offset: 0x88
    dtype: float64
    value: ${{freq}}
  phase:
    offset: 0x90
    dtype: float64
    value: 0
  P90:
    offset: 0x9c
    dtype: float32
    value: 90
  P180:
    offset: 0xa4
    dtype: float32
    value: 180
  gainRx:
    offset: 0xe4
    dtype: uint32
    value: 7
