# Wobble experiment configuration
---
description:
  A Wobble experiment.
executable: WOBBLE_FIFO_2016.elf
action:
  offset: 0x0
  values:
    stop: 0
    run: 1
status:
  offset: 0x4
  values:
    uninitialised: 1
    running: 2
    capture: 3
    finished: 10
output:
  type: FIFO
  dtype: int32
  offset: 0x100
  length: ${{steps}*{samples}}
  scale_factor: 0.00000267
parameters:
  freq:
    dtype: float64
    unit: MHz
  amp:
    offset: 0x98
    dtype: float32
    min: 0
    max: 100
    unit: '%'
    scaling: 0.01
  steps:
    offset: 0xc0
    dtype: uint32
    min: 1
  samples:
    offset: 0xc4
    dtype: uint32
    min: 1
  decimation:
    offset: 0xcc
    dtype: uint32
    min: 50
  bandwidth:
    offset: 0xd4
    dtype: float64
    unit: MHz
derived_parameters:
  ignore_samples:
    offset: 0xc8
    dtype: uint32
    value: 7
  freqTx:
    offset: 0x80
    dtype: float64
    value: ${{freq}}
  freqRx:
    offset: 0x88
    dtype: float64
    value: ${{freq}}
  phaseRx:
    offset: 0x90
    dtype: float64
    value: 0
  P90:
    offset: 0x9c
    dtype: float32
    value: 90
