# FID experiment configuration
---
description:
  A FID experiment.
executable: FID_FIFO.elf
action:
  offset: 0x0
  values:
    stop: 0
    run: 1
status:
  offset: 0x4
  values:
    uninitialised: 1
    running: 2
    capture: 3
    finished: 10
progress:
  offset: 0x1c
  limit: ${{scans}-1}
output:
  type: FIFO
  dtype: int32
  offset: 0x100
  length: ${2*{samples}}
  scale_factor: ${0.00000267*1.095/{scans}}
parameters:
  freq:
    dtype: float64
    unit: MHz
  phase:
    offset: 0x90
    dtype: float64
  amp_90:
    offset: 0x98
    dtype: float32
    min: 0
    max: 100
    unit: '%'
    scaling: 0.01
  width_90:
    offset: 0xa8
    dtype: uint32
    min: 0
    max: 500
    unit: us
    scaling: 1000
  damp_time:
    offset: 0xbc
    dtype: uint32
    min: 0.5
    unit: us
    scaling: 1000
  acq_delay:
    offset: 0xb0
    dtype: uint32
    min: 0.5
    unit: us
    scaling: 1000
  rep_time:
    offset: 0xd4
    dtype: uint64
    min: 0
    unit: s
    scaling: 1000000000
  samples:
    offset: 0xc4
    dtype: uint32
    min: 1
  dwell_time:
    offset: 0xcc
    dtype: uint32
    min: 0.5
    unit: us
    scaling: 100
  scans:
    offset: 0xd0
    dtype: uint32
    min: 1
derived_parameters:
  ignore_samples:
    offset: 0xc8
    dtype: uint32
    value: 7
  freqTx:
    offset: 0x80
    dtype: float64
    value: ${{freq}}
  freqRx:
    offset: 0x88
    dtype: float64
    value: ${{freq}}
  P90:
    offset: 0x9c
    dtype: float32
    value: 90
