# FID experiment configuration
---
description:
  A FID experiment.
executable: FID_FIFO.elf
action:
  offset: 0x0
  values:
    stop: 0
    run: 1
status:
  offset: 0x4
  values:
    uninitialised: 1
    running: 2
    capture: 3
    finished: 10
progress:
  offset: 0x1c
  limit: ${{averages}-1}
output:
  type: FIFO
  dtype: int32
  offset: 0x100
  length: ${2*{samples}}
  scale_factor: ${0.00000267/{averages}}
parameters:
  frequency:
    dtype: float64
  phaseRx:
    offset: 0x90
    dtype: float64
  A90:
    offset: 0x98
    dtype: float32
  T90:
    offset: 0xa8
    dtype: uint32
  Tdamp:
    offset: 0xd4
    dtype: uint32
  acq_delay:
    offset: 0xb0
    dtype: uint32
  Tend:
    offset: 0xbc
    dtype: uint32
  samples:
    offset: 0xc4
    dtype: uint32
  decimation:
    offset: 0xcc
    dtype: uint32
  averages:
    offset: 0xd0
    dtype: uint32
derived_parameters:
  ignore_samples:
    offset: 0xc8
    dtype: uint32
    value: 7
  freqTx:
    offset: 0x80
    dtype: float64
    value: ${{frequency}}
  freqRx:
    offset: 0x88
    dtype: float64
    value: ${{frequency}}
  P90:
    offset: 0x9c
    dtype: float32
    value: 90
