# 1D MRI program configuration
description:
  A 1D MRI experiment.
executable: 1D_MRI_DMA.elf
action:
  offset: 0x0
  values:
    stop: 0
    run: 1
status:
  offset: 0x4
  values:
    uninitialised: 1
    running: 2
    capture: 3
    finished: 10
progress:
  offset: 0x1c
  limit: ${{scans}-1}
output:
  type: DMA
  dtype: int32
  offset: 0x0
  block_count: 1
  block_length: ${2*{samples}}
  block_skip: 14
  rotbuf: true
  rotbuf_total: ${{scans}}
  rotbuf_length_offset: 0x30
  rotbuf_read_index_offset: 0x34
  rotbuf_write_index_offset: 0x38
  scale_factor: 1
adc_overflow_count:
  offset: 0x20
parameters:
  freq:
    dtype: float64
    unit: MHz
    shared: true
    group: pulse
  amp_90:
    offset: 0x98
    dtype: float32
    min: 0
    max: 100
    unit: '%'
    scaling: 0.01
    shared: true
    group: pulse
  amp_180:
    offset: 0xa0
    dtype: float32
    min: 0
    max: 100
    unit: '%'
    scaling: 0.01
    shared: true
    group: pulse
  width_90:
    offset: 0xa8
    dtype: uint32
    min: 1
    max: 500
    unit: us
    scaling: 1000
    shared: true
    group: pulse
  width_180:
    offset: 0xac
    dtype: uint32
    min: 1
    max: 500
    unit: us
    scaling: 1000
    shared: true
    group: pulse
  damp_time:
    offset: 0xbc
    dtype: uint32
    min: 1
    unit: us
    scaling: 1000
    shared: true
    group: pulse
  echo_time:
    dtype: uint32
    min: 1
    unit: us
    scaling: 1000
    group: pulse
  echo_shift:
    dtype: int32
    unit: us
    scaling: 1000
    group: acquisition
  rep_time:
    offset: 0xd4
    dtype: uint64
    min: 0
    unit: s
    scaling: 1000000000
    group: pulse
  samples:
    offset: 0xc4
    dtype: uint32
    min: 1
    max: 16000
    group: acquisition
  dwell_time:
    offset: 0xcc
    dtype: uint32
    min: 0.1
    max: 80
    unit: us
    scaling: 100
    group: acquisition
  scans:
    offset: 0xd0
    dtype: uint32
    min: 1
    group: pulse
  shim_X:
    offset: 0xec
    dtype: int32
    min: -32768
    max: 32767
    shared: true
    group: pulse
  shim_Y:
    offset: 0xf0
    dtype: int32
    min: -32768
    max: 32767
    shared: true
    group: pulse
  shim_Z:
    offset: 0xf4
    dtype: int32
    min: -32768
    max: 32767
    shared: true
    group: pulse
  GX:
    dtype: int32
    min: -32768
    max: 32767
    group: pulse
  GY:
    dtype: int32
    min: -32768
    max: 32767
    group: pulse
  GZ:
    dtype: int32
    min: -32768
    max: 32767
    group: pulse
derived_parameters:
  GX_encode:
    offset: 0xf8
    dtype: int32
    value: ${{shim_X} - {GX}}
    min: -32768
    max: 32767
  GY_encode:
    offset: 0xfc
    dtype: int32
    value: ${{shim_Y} - {GY}}
    min: -32768
    max: 32767
  GZ_encode:
    offset: 0x100
    dtype: int32
    value: ${{shim_Z} - {GZ}}
    min: -32768
    max: 32767
  GX_read:
    offset: 0x104
    dtype: int32
    value: ${{GX} + {shim_X}}
    min: -32768
    max: 32767
  GY_read:
    offset: 0x108
    dtype: int32
    value: ${{GY} + {shim_Y}}
    min: -32768
    max: 32767
  GZ_read:
    offset: 0x10c
    dtype: int32
    value: ${{GZ} + {shim_Z}}
    min: -32768
    max: 32767
  T1:
    offset: 0xb0
    dtype: uint32
    value: ${{samples}*{dwell_time}*5 + {echo_shift}}
    min: 1000
  T2:
    offset: 0xb4
    dtype: uint32
    value: ${{echo_time} - ({width_90} + {width_180} + {samples}*{dwell_time}*10)/2 - {damp_time} - {echo_shift}}
    min: 1000
  T3:
    offset: 0xb8
    dtype: uint32
    value: ${{echo_time} - ({width_180} + {samples}*{dwell_time}*10)/2 - {damp_time} + {echo_shift} - 7*{dwell_time}*10}
    min: 5000
  duty_cycle:
    value: ${({width_180}+{width_90})/{rep_time}}
    max: 0.1
  ignore_samples:
    offset: 0xc8
    dtype: uint32
    value: 7
  freqTx:
    offset: 0x80
    dtype: float64
    value: ${{freq}}
  freqRx:
    offset: 0x88
    dtype: float64
    value: ${{freq}}
  phase:
    offset: 0x90
    dtype: float64
    value: 0
  P90:
    offset: 0x9c
    dtype: float32
    value: 90
  P180:
    offset: 0xa4
    dtype: float32
    value: 180
  gainRx:
    offset: 0xe4
    dtype: uint32
    value: 7
