# CPMG experiment configuration
---
description:
  A CPMG experiment.
executable: CPMG_FIFO_phcycled_2016.elf
action:
  offset: 0x0
  values:
    stop: 0
    run: 1
status:
  offset: 0x4
  values:
    uninitialised: 1
    running: 2
    capture: 3
    finished: 10
progress:
  offset: 0x1c
  limit: ${{averages}-1}
output:
  type: FIFO
  dtype: int32
  offset: 0x100
  length: ${{loops}*{samples}}
parameters:
  freqTx:
    offset: 0x80
    dtype: float64
  freqRx:
    offset: 0x88
    dtype: float64
  phaseRx:
    offset: 0x90
    dtype: float64
  A90:
    offset: 0x98
    dtype: float32
  P90:
    offset: 0x9c
    dtype: float32
  A180:
    offset: 0xa0
    dtype: float32
  P180:
    offset: 0xa4
    dtype: float32
  T90:
    offset: 0xa8
    dtype: uint32
  T180:
    offset: 0xac
    dtype: uint32
  T1:
    offset: 0xb0
    dtype: uint32
  T2:
    offset: 0xb4
    dtype: uint32
  T3:
    offset: 0xb8
    dtype: uint32
  Tend:
    offset: 0xbc
    dtype: uint32
  loops:
    offset: 0xc0
    dtype: uint32
  samples:
    offset: 0xc4
    dtype: uint32
  ignore_samples:
    offset: 0xc8
    dtype: uint32
  decimation:
    offset: 0xcc
    dtype: uint32
  averages:
    offset: 0xd0
    dtype: uint32
