# CPMG program configuration
description:
  A CPMG experiment.
executable: CPMG_FIFO_phcycled_2016.elf
action:
  offset: 0x0
  values:
    stop: 0
    run: 1
status:
  offset: 0x4
  values:
    uninitialised: 1
    running: 2
    capture: 3
    finished: 10
progress:
  offset: 0x1c
  limit: ${{averages}-1}
output:
  type: FIFO
  dtype: int32
  offset: 0x100
  length: ${2*{loops}*{samples}}
  scale_factor: ${0.00000267/{averages}}
parameters:
  frequency:
    dtype: float64
  phaseRx:
    offset: 0x90
    dtype: float64
  A90:
    offset: 0x98
    dtype: float32
    min: 0
    max: 1
  A180:
    offset: 0xa0
    dtype: float32
    min: 0
    max: 1
  T90:
    offset: 0xa8
    dtype: uint32
    min: 0
    max: 500000
  T180:
    offset: 0xac
    dtype: uint32
    min: 0
    max: 500000
  Tdamp:
    offset: 0xd4
    dtype: uint32
    min: 500
  Techo:
    dtype: uint32
    min: 0
  echo_shift:
    dtype: int32
  Tend:
    offset: 0xbc
    dtype: uint32
    min: 0
  loops:
    offset: 0xc0
    dtype: uint32
    min: 1
  samples:
    offset: 0xc4
    dtype: uint32
    min: 1
  decimation:
    offset: 0xcc
    dtype: uint32
    min: 1
  averages:
    offset: 0xd0
    dtype: uint32
    min: 1
derived_parameters:
  T1:
    offset: 0xb0
    dtype: uint32
    value: ${({Techo} - {T90} - {Tdamp} - 2000 - {T180} - {Tdamp} - 2000)/2}
    min: 0
  T2:
    offset: 0xb4
    dtype: uint32
    value: ${({Techo} - {T180} - {Tdamp} - 2000 - {samples}*{decimation}*10)/2 + {echo_shift}}
    min: 0
  T3:
    offset: 0xb8
    dtype: uint32
    value: ${({Techo} - {T180} - {Tdamp} - 2000 + {samples}*{decimation}*10)/2 - {echo_shift}}
    min: 0
  duty_cycle:
    value: ${{T180}/{Techo}}
    max: 0.5
  ignore_samples:
    offset: 0xc8
    dtype: uint32
    value: 7
  freqTx:
    offset: 0x80
    dtype: float64
    value: ${{frequency}}
  freqRx:
    offset: 0x88
    dtype: float64
    value: ${{frequency}}
  P90:
    offset: 0x9c
    dtype: float32
    value: 90
  P180:
    offset: 0xa4
    dtype: float32
    value: 180
