freq: 2.047
phase: 0
amp_90: 25
amp_180: 50
width_90: 20
width_180: 20
rep_time: 3
echo_time: 500
echo_shift: 0
echo_count: 250
samples: 64
dwell_time: 0.5
scans: 4
bandwidth: 0.5
acq_delay: 0
damp_time: 15
