# Noise experiment configuration
---
description:
  A Noise experiment.
executable: NOISE_DMA.elf
action:
  offset: 0x0
  values:
    stop: 0
    run: 1
status:
  offset: 0x4
  values:
    uninitialised: 1
    running: 2
    capture: 3
    finished: 10
output:
  type: DMA
  dtype: int32
  offset: 0x0
  block_count: 1
  block_length: ${2*{samples}}
  block_skip: 14
  scale_factor: ${{calibration}*(2**(7-{gainRx}))}
adc_overflow_count:
  offset: 0x20
parameters:
  freq:
    dtype: float64
    unit: MHz
    shared: true
    group: acquisition
  samples:
    offset: 0xc4
    dtype: uint32
    min: 1
    max: 1000000
    group: acquisition
  dwell_time:
    offset: 0xcc
    dtype: uint32
    min: 0.1
    max: 80
    unit: us
    scaling: 100
    group: acquisition
  calibration:
    dtype: float32
    shared: true
    group: acquisition
  gainRx:
    offset: 0xe4
    dtype: uint32
    min: 0
    max: 15
    unit: x3 dB
    group: acquisition
    shared: true
derived_parameters:
  ignore_samples:
    offset: 0xc8
    dtype: uint32
    value: 7
  freqRx:
    offset: 0x88
    dtype: float64
    value: ${{freq}}
