# Noise experiment configuration
---
description:
  A Noise experiment.
executable: NOISE_FIFO.elf
action:
  offset: 0x0
  values:
    stop: 0
    run: 1
status:
  offset: 0x4
  values:
    uninitialised: 1
    running: 2
    capture: 3
    finished: 10
output:
  type: FIFO
  dtype: int32
  offset: 0x100
  length: ${2*{samples}}
  scale_factor: ${0.00000267*1.095}
adc_overflow_count:
  offset: 0x20
parameters:
  freq:
    dtype: float64
    unit: MHz
    shared: true
    group: acquisition
  samples:
    offset: 0xc4
    dtype: uint32
    min: 1
    max: 16000
    group: acquisition
  dwell_time:
    offset: 0xcc
    dtype: uint32
    min: 0.5
    unit: us
    scaling: 100
    group: acquisition
derived_parameters:
  ignore_samples:
    offset: 0xc8
    dtype: uint32
    value: 7
  freqRx:
    offset: 0x88
    dtype: float64
    value: ${{freq}}