# Noise experiment configuration
---
description:
  A Noise experiment.
executable: NOISE_SCAN.elf
action:
  offset: 0x0
  values:
    stop: 0
    run: 1
status:
  offset: 0x4
  values:
    uninitialised: 1
    running: 2
    capture: 3
    finished: 10
output:
  type: FIFO
  dtype: int32
  offset: 0x100
  length: 8192
  scale_factor: 0.00000267
parameters: {}