# Wobble experiment configuration
---
description:
  A Wobble experiment.
executable: WOBBLE_FIFO.elf
action:
  offset: 0x0
  values:
    stop: 0
    run: 1
status:
  offset: 0x4
  values:
    uninitialised: 1
    running: 2
    capture: 3
    finished: 10
progress:
  offset: 0x1c
  limit: 100
output:
  type: FIFO
  dtype: int32
  offset: 0x100
  length: ${{steps}*{samples}}
  scale_factor: 1
adc_overflow_count:
  offset: 0x20
parameters:
  freq:
    dtype: float64
    unit: MHz
    shared: true
    group: pulse
  amp:
    offset: 0x98
    dtype: float32
    min: 0
    max: 100
    unit: '%'
    scaling: 0.01
    group: pulse
  steps:
    offset: 0xc0
    dtype: uint32
    min: 1
    group: pulse
  samples:
    offset: 0xc4
    dtype: uint32
    min: 1
    max: 16000
    group: acquisition
  dwell_time:
    offset: 0xcc
    dtype: uint32
    min: 0.5
    unit: us
    scaling: 100
    group: acquisition
  bandwidth:
    offset: 0xdc
    dtype: float64
    unit: MHz
    group: pulse
derived_parameters:
  ignore_samples:
    offset: 0xc8
    dtype: uint32
    value: 7
  freqTx:
    offset: 0x80
    dtype: float64
    value: ${{freq}}
  freqRx:
    offset: 0x88
    dtype: float64
    value: ${{freq}}
  phaseRx:
    offset: 0x90
    dtype: float64
    value: 0
  P90:
    offset: 0x9c
    dtype: float32
    value: 90
